### ISSUE TITLE
Integration with pandas-profiling

### ISSUE THREAD

**Issue by sbrugman** [luiztauffer/pandasVIS#1]
Hi Luiz, Great idea to create a PyQt GUI for pandas-profiling and extending the visualisation of interactions. I'm sure some of our current users would really appreciate these additions. Are you interested in sharing your creations with them?

In the package, the [controller](https://github.com/pandas-profiling/pandas-profiling/tree/master/pandas_profiling/controller) would be the place to add the GUI.

**Comment by luiztauffer** [comment]
Hi @sbrugman , thanks for getting in touch!
My idea with PandasVIS is to integrate many visualization and data exploration tools, such as pandas-profiling, in a GUI. It’s not really built around pandas-profiling, but rather makes use of it for one type of reporting. Right now I'm working on some more complex plot grids using Plotly, for example. Later I hope to integrate ML tools with full reports as well. 
In that sense, I think it escapes pandas-profiling scope. Or am I wrong?
But of course I would be happy to share it with others and accept suggestions and collaborations! If you/others think of better ways to present pandas-profiling reports in the gui, for example!
Let me know if you’d like me to share the link to the repo somewhere or else feel free to link it as well!

**Comment by sbrugman** [comment]
PandasVIS fits nicely in the new generation of tools that come available for data analysis. You are right that pandas-profiling has a strong focus on exploratory data analysis (EDA) for a larger audience. There is a touching point between the projects however, where we could add a GUI style (PyQt) to pandas-profiling. This would allow PandasVIS to extend pandas-profiling and other visualization and exploration tools, with a more native look (without the HTML frame). 

The soon to release pandas-profiling v3 will provide a framework for this, if you are interested in collaboration in this area, just open an issue (or shoot an email to pandasprofiling@gmail.com).
